name: schedule API example

on: 
  schedule:
    - cron: '* * * * *'
jobs:
  post-API:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET 'https://jsonplaceholder.typicode.com/posts/1'

