name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  repository_dispatch:
  schedule:
    - cron: '3 * * * *'
jobs:
  post-API:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://jsonplaceholder.typicode.com/posts/1"

