name: schedule API example

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  post-API:
    runs-on: ubuntu-latest
    env:
      CODE: 3tXqNi6tol5h1ur-gH1HXJAOER9-zKaZ4AzcOvzbDDAzFuO3yzAg==
   
    steps:
    - name: actions checkout
      uses: actions/checkout@v3

    - name: envs, secrets and random
      run: |
        node -e "console.log(Math.floor(Math.random() * 99999))" 
        !concat [Math.floor(Math.random() * 99999), "world"]
    - name: post api call
      run: |
        echo extracting data.json
        curl -d "@./payload/data.json" -X POST https://gitonfunc.azuresites.net/api/HttpTrigger1?code=$CODE

