name: schedule API example

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  post-API:
    runs-on: ubuntu-latest
    env:
      CODE: 3tXqNi6tol5h1ur-gH1HXJAOER9-zKaZ4AzcOvzbDDAzFuO3yzAg==
      REQID: abcdef
      TEMP: node -e "console.log(abcdef + Math.floor(Math.random() * 99999))"

   
    steps:
    - name: actions checkout
      uses: actions/checkout@v3

    - name: envs, secrets and random
      run: |
        echo ${{secrets.KEY}}
        echo $CODE
        node -e "console.log(Math.floor(Math.random() * 99999))"
    - name: post api call
      run: |
        node -e "{{Math.floor(Math.random() * 99999)}}"
        node -e {{Math.floor(Math.random() * 99999)}}
        echo extracting data.json
        curl -d "@./payload/data.json" -X POST https://gitonfunc.azuresites.net/api/HttpTrigger1?code=$CODE

